/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author ragne
 */
public class addBooking extends javax.swing.JFrame {

    /**
     * Creates new form addBooking
     */
    public addBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookingIDtxt = new javax.swing.JTextField();
        roomIDtxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        timeLst = new javax.swing.JComboBox<>();
        personTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        monthTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        backBtn.setText("Go Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Booking");

        jLabel2.setText("Booking ID:");

        jLabel3.setText("Room ID:");

        jLabel4.setText("Date:");

        jLabel5.setText("Time:");

        jLabel6.setText("Contact Person:");

        jLabel7.setText("Contact Email:");

        jLabel8.setText("Contact Phone:");

        bookingIDtxt.setEditable(false);

        roomIDtxt.setEditable(false);

        dateTxt.setText("DD");
        dateTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTxtFocusLost(evt);
            }
        });

        timeLst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00-11:00", "11:00-13:00", "13:00-15:00", "15:00-17:00", "09:00-13:00(Morning)", "13:00-17:00(Afternoon)", "09:00-17:00(All Day)" }));

        submitBtn.setBackground(new java.awt.Color(255, 204, 204));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("/");

        monthTxt.setText("MM");
        monthTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthTxtFocusLost(evt);
            }
        });

        jLabel10.setText("/");

        yearTxt.setText("YY");
        yearTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearTxtFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(42, 42, 42)
                                        .addComponent(bookingIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(54, 54, 54)
                                        .addComponent(roomIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(timeLst, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(personTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(backBtn)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(20, 20, 20)
                                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(phoneTxt))))))))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtn)
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(bookingIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(roomIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timeLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(609, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //back button method
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        bookingMenu obj = new bookingMenu();//new instance of bookingMenu
        obj.setVisible(true);//make bookingMenu visible
        this.setVisible(false);////make current window invisible

    }//GEN-LAST:event_backBtnActionPerformed
    //submit button method
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        // Get the booking ID entered in the bookingIDtxt field and convert it to an integer
        int bookingID = Integer.parseInt(bookingIDtxt.getText());

        // Get the room ID entered in the roomIDtxt field
        String roomID = roomIDtxt.getText();

        try {
            // Check if the entered bookingID already exists in the list of bookings
            for (bookingClass booking : AppLib.bookingClasslst) {
                if (booking.getBookingID() == bookingID) {
                    // Display an error message if the bookingID already exists
                    JOptionPane.showMessageDialog(rootPane, "***BookingID already exists***\nPlease try again", "Error Message", JOptionPane.ERROR_MESSAGE);
                }
            }

            // Get the day, month, and year components from the corresponding text fields
            int day = Integer.parseInt(dateTxt.getText());
            int month = Integer.parseInt(monthTxt.getText());
            int year = Integer.parseInt(yearTxt.getText());

            // Create a formatted date string using the day, month, and year
            String date = day + "/" + month + "/" + year;

            // Get the selected time from the timeLst dropdown
            String time = timeLst.getSelectedItem().toString();

            // Get the contact person, email, and phone number entered in the text fields
            String contactPerson = personTxt.getText();
            String contactEmail = emailTxt.getText();
            String contactPhone = phoneTxt.getText();

            // Validate the entered day, month, and year against specific criteria
            if (day < 1 || day > 31) {
                JOptionPane.showMessageDialog(rootPane, "DD must be between 1 and 31", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if day is invalid
            }

            if (month < 1 || month > 12) {
                JOptionPane.showMessageDialog(rootPane, "MM must be between 1 and 12", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if month is invalid
            }

            if (year < 2024 || year > 2025) {
                JOptionPane.showMessageDialog(rootPane, "We are only taking bookings in the academic year 2024-2025\n Please change YY to correct year", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if year is invalid
            }

            // Validate that the contact person contains only letters (no digits)
            if (contactPerson.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(rootPane, "Contact Person must only contain letters", "Error Message", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if contact person contains digits
            }

            // Validate the contact email format
            if (!contactEmail.contains("@") || !contactEmail.contains(".com")) {
                JOptionPane.showMessageDialog(rootPane, "Contact Email must contain '@email.com'", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if contact email format is invalid
            }

            // Validate the contact phone number format and length
            if (contactPhone.length() != 11 || !contactPhone.matches("\\d+")) {
                JOptionPane.showMessageDialog(rootPane, "Contact Phone must contain 11 numbers only", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if contact phone number format is invalid
            }

            // Create a new bookingClass object with the validated data
            bookingClass obj = new bookingClass(bookingID, roomID, date, time, contactPerson, contactEmail, contactPhone);

            // Add the new booking to the list of bookings
            AppLib.bookingClasslst.add(obj);

            // Display a success message with details of the added booking
            JOptionPane.showMessageDialog(rootPane, "\nBooking added Successfully\n"
                    + "Booking ID: " + bookingID + "\nRoom ID: " + roomID + "\nDate: " + date
                    + "\nTime: " + time + "\nContact Person: " + contactPerson
                    + "\nContact Email: " + contactEmail + "\nContact Phone: " + contactPhone);
        } catch (Exception e) {
            // Catch any exceptions (e.g., invalid input) and display an error message
            JOptionPane.showMessageDialog(rootPane, "***Incorrect Values***\nPlease try again", "Error Message", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_submitBtnActionPerformed

    private addBooking exit;
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // Create a new instance of the addBooking class
        exit = new addBooking();

        // Display a confirmation dialog asking the user if they want to exit
        if (JOptionPane.showConfirmDialog(exit, "Confirm if you want to exit", "Booking System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // If the user confirms (chooses "Yes"), exit the application
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Initialize a Random object to generate random numbers
        Random random = new Random();

        // Generate two random numbers between 0 and 99999
        int rand = random.nextInt(99999);
        int rand2 = random.nextInt(99999);

        // Set the generated random number as the text for bookingIDtxt field
        this.bookingIDtxt.setText(String.valueOf(rand));

        // Create a room ID string combining "RM-" and the second generated random number
        String roomID = "RM-" + rand2;

        // Set the roomIDtxt field with the created room ID
        this.roomIDtxt.setText(roomID);
    }//GEN-LAST:event_formWindowOpened

    private void yearTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTxtFocusGained
        // Check if the yearTxt field contains the placeholder text "YY" when it gains focus
        if (yearTxt.getText().equals("YY")) {
            // If true, clear the placeholder text
            yearTxt.setText("");
        }
    }//GEN-LAST:event_yearTxtFocusGained

    private void yearTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTxtFocusLost
        // Check if the yearTxt field is empty when it loses focus
        if (yearTxt.getText().equals("")) {
            // If true, restore the placeholder text "YY"
            yearTxt.setText("YY");
        }
    }//GEN-LAST:event_yearTxtFocusLost

    private void monthTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTxtFocusGained
        // Check if the monthTxt field contains the placeholder text "MM" when it gains focus
        if (monthTxt.getText().equals("MM")) {
            // If true, clear the placeholder text
            monthTxt.setText("");
        }
    }//GEN-LAST:event_monthTxtFocusGained

    private void monthTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTxtFocusLost
        // Check if the monthTxt field is empty when it loses focus
        if (monthTxt.getText().equals("")) {
            // If true, restore the placeholder text "MM"
            monthTxt.setText("MM");
        }
    }//GEN-LAST:event_monthTxtFocusLost

    private void dateTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTxtFocusGained
        // Check if the dateTxt field contains the placeholder text "DD" when it gains focus
        if (dateTxt.getText().equals("DD")) {
            // If true, clear the placeholder text
            dateTxt.setText("");
        }
    }//GEN-LAST:event_dateTxtFocusGained

    private void dateTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTxtFocusLost
        // Check if the dateTxt field is empty when it loses focus
        if (dateTxt.getText().equals("")) {
            // If true, restore the placeholder text "DD"
            dateTxt.setText("DD");
        }
    }//GEN-LAST:event_dateTxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bookingIDtxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monthTxt;
    private javax.swing.JTextField personTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField roomIDtxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JComboBox<String> timeLst;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
